MCU = RP2040
BOOTLOADER = rp2040

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

I2C1_SDA_PIN = GP18
I2C1_SCL_PIN = GP19

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
VIA_ENABLE = yes  # If you want VIA support
